# Generated by Django 4.0.2 on 2022-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iviApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='overview',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
